"""add manual stream url

Revision ID: 5007c70076ea
Revises: 57e8ccd29130
Create Date: 2026-08-24 09:01:44.745011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5007c70076ea'
down_revision: Union[str, None] = '57e8ccd29130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_channels', sa.Column('manual_stream_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_channels', 'manual_stream_url')
    # ### end Alembic commands ###
