"""initial schema

Revision ID: 57e8ccd29130
Revises: 
Create Date: 2026-08-24 08:58:17.282307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57e8ccd29130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('epg_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_status', sa.String(length=20), nullable=True),
    sa.Column('last_refresh_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epg_sources_name'), 'epg_sources', ['name'], unique=True)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('xc_enabled', sa.Boolean(), nullable=False),
    sa.Column('m3u_output_enabled', sa.Boolean(), nullable=False),
    sa.Column('m3u_filename', sa.String(length=255), nullable=False),
    sa.Column('epg_output_enabled', sa.Boolean(), nullable=False),
    sa.Column('epg_filename', sa.String(length=255), nullable=False),
    sa.Column('epg_days_to_keep', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('m3u_url', sa.Text(), nullable=True),
    sa.Column('m3u_uses_userpass', sa.Boolean(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('suffix', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('ignore_vod', sa.Boolean(), nullable=False),
    sa.Column('ignore_series', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_on_start', sa.Boolean(), nullable=False),
    sa.Column('auto_enable_new_groups', sa.Boolean(), nullable=False),
    sa.Column('auto_clear_removed_days', sa.Integer(), nullable=True),
    sa.Column('provider_uses_tokens', sa.Boolean(), nullable=False),
    sa.Column('use_api_for_series', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_sources', sa.Boolean(), nullable=False),
    sa.Column('sync_epg', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xc_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xc_users_username'), 'xc_users', ['username'], unique=True)
    op.create_table('epg_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epg_source_id', sa.Integer(), nullable=False),
    sa.Column('epg_channel_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['epg_source_id'], ['epg_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epg_channels_epg_channel_id'), 'epg_channels', ['epg_channel_id'], unique=False)
    op.create_index(op.f('ix_epg_channels_epg_source_id'), 'epg_channels', ['epg_source_id'], unique=False)
    op.create_table('playlist_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('dummy_epg_for_unassigned', sa.Boolean(), nullable=False),
    sa.Column('dummy_epg_program_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_categories_playlist_id'), 'playlist_categories', ['playlist_id'], unique=False)
    op.create_table('source_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_categories_source_id'), 'source_categories', ['source_id'], unique=False)
    op.create_table('xc_user_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xc_user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['xc_user_id'], ['xc_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xc_user_id', 'playlist_id')
    )
    op.create_index(op.f('ix_xc_user_playlists_playlist_id'), 'xc_user_playlists', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_xc_user_playlists_xc_user_id'), 'xc_user_playlists', ['xc_user_id'], unique=False)
    op.create_table('epg_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epg_channel_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stop', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('subtitle', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['epg_channel_id'], ['epg_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epg_programs_epg_channel_id'), 'epg_programs', ['epg_channel_id'], unique=False)
    op.create_index(op.f('ix_epg_programs_start'), 'epg_programs', ['start'], unique=False)
    op.create_table('playlist_category_source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_category_id', sa.Integer(), nullable=False),
    sa.Column('source_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_category_id'], ['playlist_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_category_id'], ['source_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_category_id', 'source_category_id')
    )
    op.create_index(op.f('ix_playlist_category_source_links_playlist_category_id'), 'playlist_category_source_links', ['playlist_category_id'], unique=False)
    op.create_index(op.f('ix_playlist_category_source_links_source_category_id'), 'playlist_category_source_links', ['source_category_id'], unique=False)
    op.create_table('source_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_category_id', sa.Integer(), nullable=False),
    sa.Column('external_stream_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('stream_type', sa.String(length=20), nullable=False),
    sa.Column('tvg_id', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('container_extension', sa.String(length=20), nullable=True),
    sa.Column('stream_url', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_category_id'], ['source_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_channels_external_stream_id'), 'source_channels', ['external_stream_id'], unique=False)
    op.create_index(op.f('ix_source_channels_source_category_id'), 'source_channels', ['source_category_id'], unique=False)
    op.create_table('playlist_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_category_id', sa.Integer(), nullable=False),
    sa.Column('source_channel_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_locked', sa.Boolean(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('logo_url_override', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('epg_channel_id', sa.Integer(), nullable=True),
    sa.Column('epg_match_type', sa.String(length=20), nullable=False),
    sa.Column('dummy_epg_mode', sa.String(length=20), nullable=False),
    sa.Column('dummy_epg_program_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['epg_channel_id'], ['epg_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playlist_category_id'], ['playlist_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['source_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_channels_epg_channel_id'), 'playlist_channels', ['epg_channel_id'], unique=False)
    op.create_index(op.f('ix_playlist_channels_playlist_category_id'), 'playlist_channels', ['playlist_category_id'], unique=False)
    op.create_index(op.f('ix_playlist_channels_source_channel_id'), 'playlist_channels', ['source_channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_channels_source_channel_id'), table_name='playlist_channels')
    op.drop_index(op.f('ix_playlist_channels_playlist_category_id'), table_name='playlist_channels')
    op.drop_index(op.f('ix_playlist_channels_epg_channel_id'), table_name='playlist_channels')
    op.drop_table('playlist_channels')
    op.drop_index(op.f('ix_source_channels_source_category_id'), table_name='source_channels')
    op.drop_index(op.f('ix_source_channels_external_stream_id'), table_name='source_channels')
    op.drop_table('source_channels')
    op.drop_index(op.f('ix_playlist_category_source_links_source_category_id'), table_name='playlist_category_source_links')
    op.drop_index(op.f('ix_playlist_category_source_links_playlist_category_id'), table_name='playlist_category_source_links')
    op.drop_table('playlist_category_source_links')
    op.drop_index(op.f('ix_epg_programs_start'), table_name='epg_programs')
    op.drop_index(op.f('ix_epg_programs_epg_channel_id'), table_name='epg_programs')
    op.drop_table('epg_programs')
    op.drop_index(op.f('ix_xc_user_playlists_xc_user_id'), table_name='xc_user_playlists')
    op.drop_index(op.f('ix_xc_user_playlists_playlist_id'), table_name='xc_user_playlists')
    op.drop_table('xc_user_playlists')
    op.drop_index(op.f('ix_source_categories_source_id'), table_name='source_categories')
    op.drop_table('source_categories')
    op.drop_index(op.f('ix_playlist_categories_playlist_id'), table_name='playlist_categories')
    op.drop_table('playlist_categories')
    op.drop_index(op.f('ix_epg_channels_epg_source_id'), table_name='epg_channels')
    op.drop_index(op.f('ix_epg_channels_epg_channel_id'), table_name='epg_channels')
    op.drop_table('epg_channels')
    op.drop_index(op.f('ix_xc_users_username'), table_name='xc_users')
    op.drop_table('xc_users')
    op.drop_table('sync_schedules')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_epg_sources_name'), table_name='epg_sources')
    op.drop_table('epg_sources')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
