"""add source category sort order

Revision ID: c644b625347b
Revises: 5007c70076ea
Create Date: 2026-08-24 13:39:19.449990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c644b625347b'
down_revision: Union[str, None] = '5007c70076ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (real deployments already have data here); the
    # model's Python-side default=0 only applies to new INSERTs, not existing rows.
    op.add_column(
        'source_categories', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0')
    )
    op.alter_column('source_categories', 'sort_order', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_categories', 'sort_order')
    # ### end Alembic commands ###
